---
title: "R-universe Documentation"
comments: False
---

```{r}
#| results: 'asis'
#| echo: FALSE

pitch <- readLines("https://raw.githubusercontent.com/ropensci/roweb3/refs/heads/main/content/r-universe/_index.md")
  
pitch <- pitch[(which(pitch == "+++")[2] + 1): length(pitch)]
cat(pitch, sep = "\n")

```

Find out more context, and recent videos, on the [project page on the rOpenSci website](https://ropensci.org/r-universe). 

### Using this guide {.unnumbered}

Are you...

- An R user that just wants to search something or retrieve information;
- A package developer;
- A universe developer (aka r-multiverse /pharmaverse /biocondctor or similar people); 
- Someone willing to contribute to r-universe to improve the infrastructure or documentation?

This documentation should help. 
Use the table of contents on the left, and please contribute (next section) if anything is unclear or missing!

### Contributing to this guide {.unnumbered}

We welcome contributions to this guide.

- For small changes, please open a [pull request](https://github.com/r-universe-org/docs).
- To suggest larger changes, open an [issue](https://github.com/r-universe-org/docs/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen). We may invite you to create the changes or implement them on your behalf.

Make sure to read our [contributing guide](https://github.com/r-universe-org/docs/blob/main/.github/CONTRIBUTING.md) before getting started.

### Acknowledgements and licence {.unnumbered}

We're grateful for reviewers of this documentation website:

- [Lluís Revilla](https://github.com/llrs)
- [Yaoxiang Li](https://github.com/YaoxiangLi)

This website is licensed under the [CC BY-NC-ND 4.0 License](https://creativecommons.org/licenses/by-nc-nd/4.0/).
