---
title: "Why publish on R-universe"
---

## Highlight your packages and expertise

Registering your packages with R-universe makes them easier for users to [discover and evaluate](/browse/get-started.html).  

Creating an R-universe for yourself or your organization showcases your expertise, interests, and contributions to the R community.  

## Simplify installation for your users

R-universe builds [binaries for release versions of the most popular platforms](/install/binaries.html), ensuring your packages are easy to install across systems. 
You can use R-universe to distribute an easy-to-install development version of your package between releases on other networks like [CRAN](#newer-than-cran).

## Get inspired by success stories

Read or watch interviews of the series [Meeting the stars of the R-Universe](https://ropensci.org/blog/2023/11/06/r-universe-stars-finale/), that are examples of organizations and teams that choose R-Universe to facilitate access and promote community sharing of data and software.

## Build upon R-universe

As an example of an initiative based on R-universe, 
[R-multiverse](https://r-multiverse.org/) is a new initiative to establish a trustworthy, community-curated R package repository that runs on the open-source r-universe infrastructure.

## Enjoy it for free!

R-universe is provided free of charge.

## Set up in just a few steps

Follow the [set-up documentation](/publish/set-up.html) to get started quickly.  
