---
title: "Make your package easier to discover: Control the metadata / SEO"
---

## Package metadata

### Basic information in DESCRIPTION

The first step towards making your package easier to find by search is to polish those DESCRIPTION fields:

- **Description**  
- **Details**  
- **URL**: Include your R-universe URL. [Example](https://github.com/r-lib/gert/blob/e5030397517a8658ade1d82a6edd788cf7e935da/DESCRIPTION#L16-L17)  

### How to add keyword labels to an R package? {#keywords}

R-universe's [search algorithm](#rank) leverages keywords associated with a package.  

- **For GitHub-hosted packages**: Add keywords using [repository topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics).  
- **For any package, including CRAN-compliant packages**: Use the `X-schema.org-keywords` field in the `DESCRIPTION` file. This field is [CRAN-permitted](https://cs.github.com/?q=org%3Acran+X-schema.org-keywords).  

Additionally, the build system may automatically generate keywords based on package analysis, including linked system libraries or language tags like `c++` or `openmp`.  

### How to increase the rank of a package? {#better-rank}

Your package’s rank in search results depends on its [ranking algorithm](#rank).  
To improve ranking:  
- Gain more GitHub stars.  
- Follow strategies from the blog post ["Marketing Ideas For Your Package"](https://ropensci.org/blog/2024/03/07/package-marketing/).  

### How to get a package logo shown in the packages tab?

R-universe uses `pkgdown` conventions to detect package logos:  
- Place the logo in `man/figures/logo.png` or `man/figures/logo.svg`, which can be checked by `pkgdown:::find_logo()`.
- Alternatively, specify the logo as an opengraph image in your `_pkgdown.yml`.  

## Individual (contributor, maintainer) metadata

### How to link a maintainer email addresses to a username on R-universe?

R-universe associates maintainers with their GitHub usernames based on email addresses.  

- Use the same email address in your `DESCRIPTION` file’s maintainer field or commits as the one registered on GitHub.  
- If you use multiple email addresses, add them to your [GitHub settings](https://github.com/settings/emails).  

Once the email is validated on GitHub, future builds of your packages will reflect the association. Note that changes take effect after the next package build.  

### My profile picture or contributor statistics do not show up

If your profile picture or contributor statistics are not visible:  
1. Ensure the email used in the package `DESCRIPTION` file is registered in your [GitHub settings](https://github.com/settings/emails).  
2. Wait for the next package rebuild for the changes to be reflected. 

