---
title: "Relation to other networks"
---

## Relation to other networks

Packages on R-universe may also exist on other networks, such as CRAN or Bioconductor.

It's important to note that CRAN is not intended to be the sole CRAN-style package repository, as [explained by CRAN co-founder Kurt Hornik in his useR! 2024 keynote](https://static.sched.com/hosted_files/userconf2024/41/user2024_CRAN.pdf#page=8).  

## Can we use R-universe to host older versions of CRAN packages?

While hosting older versions of CRAN packages on R-universe is technically possible, it may not work as intended.  

- R's `install.packages()` and `update.packages()` functions will always install the latest version of a package available across all configured repositories.  
- As a result, the older version hosted on R-universe might be automatically updated to the latest CRAN version on the user’s machine.  

## Can we use R-universe to host newer versions of CRAN packages? {#newer-than-cran}

Yes, you can use R-universe to distribute the development version of your package between CRAN releases.
It is one of the intended use cases for R-universe.

## Can we use R-universe to host a fork of a CRAN package?

Hosting a fork of a CRAN package on R-universe is possible but generally not recommended.

- The CRAN version of the package may overwrite your fork when the user runs `install.packages()` or `update.packages()`.  
- Additionally, other packages depending on the original CRAN package may not be compatible with your fork, leading to potential issues.  
