---
title: "Using dependencies from R-universe"
---

## CRAN-like repository URLs

R-universe provides CRAN-like repository URLs for each universe.
For example, the following functions work:

```r
# All the packages in the tidyverse universe
available.packages(repos = "https://tidyverse.r-universe.dev")

# Installs dplyr and its dependencies from the tidyverse universe,
# and its dependencies does not exist in the tidyverse universe are installed from CRAN
install.packages("dplyr", repos = c("https://tidyverse.r-universe.dev", "https://cloud.r-project.org"))
```

If you want to install only specific packages from the universe, and install the other packages from CRAN,
you can specify the repository for only the package you want to install from the universe as follows:

```r
# Package specific repository for dplyr
available.packages(repos = "https://tidyverse.r-universe.dev/dplyr")

# Installs dplyr from the tidyverse universe,
# and its dependencies are installed from CRAN
install.packages("dplyr", repos = c("https://tidyverse.r-universe.dev/dplyr", "https://cloud.r-project.org"))
```

To install binary versions, append `bin/linux/...` to the URL.
See [Linux binaries](#binaries-linux) for details.
Combine with Posit Package Manager repositories for binaries for CRAN versions.

```r
# All tidyverse binaries on Ubuntu Noble for ARM for R 4.5:
install.packages("dplyr", repos = "https://tidyverse.r-universe.dev/bin/linux/noble-arm64/4.5")

# Only dplyr on Ubuntu Noble for ARM for R 4.5:
install.packages("dplyr", repos = "https://tidyverse.r-universe.dev/dplyr/bin/linux/noble-arm64/4.5")
```

## Can a CRAN package take on a dependency from R-universe?

Yes! It has to be an optional dependency (`Suggests`) and you need to

- List the R-universe in the `Additional_repositories` field in `DESCRIPTION`. [Examples of CRAN packages doing so](https://github.com/search?q=org%3Acran+path%3ADESCRIPTION+additional_repositories%3A+r-universe.dev&type=code). The field will *not* ensure installation of the package. Its sole purpose is allowing CRAN to check the package is indeed available in that other repository.

- Alternatively, if you are ok getting a NOTE from R CMD check (that you can explain in cran-comments.md) list the URL where to install the package somewhere else in `DESCRIPTION` ([example](https://github.com/cran/prioritizr/blob/0738fe58f55c812a3023e81398d4294487a8c497/DESCRIPTION#L21)).

- Document, for the user, how to install the missing package. You can do that 
    - In user-facing documentation (README, package-level manual page, manual page of the functions that use the dependency). [Example](https://github.com/ropensci/usaboundaries?tab=readme-ov-file#installation).
    - Within the code, for instance:
    
```r
if (!(require("targets"))) {
  stop("You can install targets with install.packages('targets', repos = c('https://ropensci.r-universe.dev', 'https://cloud.r-project.org'))")
}

```

or a solution that will automatically prompt the user to install the missing package:
    
```r
rlang::check_installed("targets", action = function(...) install.packages('targets', repos = c('https://ropensci.r-universe.dev', 'https://cloud.r-project.org')))
```

## How to use a universe on regular continous integration?

If you want to test a package against versions of other packages that are in a universe, on GitHub Actions you can use the [`extra-repositories` field of the `r-lib/actions` setup-r action](https://github.com/r-lib/actions/tree/v2-branch/setup-r#inputs).
