---
title: "A catalogue of R packages"
---

R-universe serves as your gateway to discovering a wide variety of R packages.  
R-universe is a collection of **universes**, each representing the packages maintained by an individual or team.  

You can search for packages and evaluate them using the detailed information provided on universe and package pages.  
Explore the three levels of navigation within R-universe:

- [Search the entire R ecosystem](/browse/search.html)
- [Browse work from a specific maintainer or organization](/browse/universes.html)
- [Access detailed information about individual packages](/browse/packages.html)

:::{.callout-caution}
R-universe does not vet packages; it is an open publishing system. 
The platform builds and deploys R packages from Git repositories into installation repositories.  
The responsibility for policies and quality control lies solely with the owner of each universe.  
:::

Stay up-to-date with the latest developments by following [RSS feeds](/browse/rss-feeds.html).  
